-- Public Vendor KYC website compatibility and duplicate protection.
-- Sensitive files remain private and use paths beginning with the authenticated vendor_id.

ALTER TABLE public.vendor_kyc_applications
  ADD COLUMN IF NOT EXISTS business_registration_document_url text;

CREATE TABLE IF NOT EXISTS public.vendor_public_rate_limits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope text NOT NULL,
  subject_hash text NOT NULL,
  attempted_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_vendor_public_rate_limits_lookup
  ON public.vendor_public_rate_limits (scope, subject_hash, attempted_at DESC);

ALTER TABLE public.vendor_public_rate_limits ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.vendor_public_rate_limits FROM anon, authenticated;
GRANT ALL ON public.vendor_public_rate_limits TO service_role;

CREATE UNIQUE INDEX IF NOT EXISTS idx_vendor_kyc_one_active_application
  ON public.vendor_kyc_applications (vendor_id, application_type)
  WHERE application_type = 'kyc' AND status IN ('pending', 'processing');

ALTER TABLE public.vendor_kyc_applications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Vendor can view own KYC applications" ON public.vendor_kyc_applications;
CREATE POLICY "Vendor can view own KYC applications"
ON public.vendor_kyc_applications FOR SELECT TO authenticated
USING (
  vendor_id IN (
    SELECT vendor_id FROM public.vendors WHERE auth_user_id = auth.uid()
  )
);

-- Final KYC inserts are performed by vendor-kyc-signatures only after Digital
-- Signatures are verified. Removing direct authenticated inserts prevents a
-- browser from forging the verified timestamp columns.
DROP POLICY IF EXISTS "Vendor can insert own KYC applications" ON public.vendor_kyc_applications;
REVOKE INSERT, UPDATE, DELETE ON public.vendor_kyc_applications FROM authenticated;
GRANT SELECT ON public.vendor_kyc_applications TO authenticated;

UPDATE storage.buckets
SET
  public = false,
  file_size_limit = 4194304,
  allowed_mime_types = ARRAY[
    'application/pdf',
    'image/jpeg',
    'image/png',
    'image/webp'
  ]
WHERE id = 'vendor-kyc-documents';

DROP POLICY IF EXISTS "Vendor can read own KYC documents" ON storage.objects;
DROP POLICY IF EXISTS "Vendor can upload own KYC documents" ON storage.objects;
DROP POLICY IF EXISTS "Vendor can update own KYC documents" ON storage.objects;
DROP POLICY IF EXISTS "Vendor can delete own KYC documents" ON storage.objects;

CREATE POLICY "Vendor can read own KYC documents"
ON storage.objects FOR SELECT TO authenticated
USING (
  bucket_id = 'vendor-kyc-documents'
  AND (storage.foldername(name))[1] IN (
    SELECT vendor_id::text FROM public.vendors WHERE auth_user_id = auth.uid()
  )
);

CREATE POLICY "Vendor can upload own KYC documents"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (
  bucket_id = 'vendor-kyc-documents'
  AND (storage.foldername(name))[1] IN (
    SELECT vendor_id::text FROM public.vendors WHERE auth_user_id = auth.uid()
  )
);

CREATE POLICY "Vendor can update own KYC documents"
ON storage.objects FOR UPDATE TO authenticated
USING (
  bucket_id = 'vendor-kyc-documents'
  AND (storage.foldername(name))[1] IN (
    SELECT vendor_id::text FROM public.vendors WHERE auth_user_id = auth.uid()
  )
)
WITH CHECK (
  bucket_id = 'vendor-kyc-documents'
  AND (storage.foldername(name))[1] IN (
    SELECT vendor_id::text FROM public.vendors WHERE auth_user_id = auth.uid()
  )
);

CREATE POLICY "Vendor can delete own KYC documents"
ON storage.objects FOR DELETE TO authenticated
USING (
  bucket_id = 'vendor-kyc-documents'
  AND (storage.foldername(name))[1] IN (
    SELECT vendor_id::text FROM public.vendors WHERE auth_user_id = auth.uid()
  )
);
